Bunch of work
Added instal scripts and commit hook

diff --git a/bin/git_update_with_upstream b/bin/git_update_with_upstream
--- a/bin/git_update_with_upstream
+++ b/bin/git_update_with_upstream
@@ -1,11 +1,16 @@
 #!/bin/bash
 # Make local repo in sync with upstream
 
+BRANCH=$1
+if [[ "x$BRANCH" = "x" ]];
+then
+  echo "Missing BRANCH"
+  echo "$0 [BRANCH]"
+  echo "$0 8.0"
+  exit 1
+fi
 REMOTE_NAME="percona"
 git fetch ${REMOTE_NAME}
-for branch in 5.6 5.7 8.0;
-do
-  git checkout ${branch} &&
-  git merge ${REMOTE_NAME}/${branch} &&
-  git push origin
-done
+git checkout ${BRANCH} &&
+git merge ${REMOTE_NAME}/${BRANCH} &&
+git push origin
